x = 5;
y = 6;
z = 7;
a = x + y + z;
console.log(a);
var a = 10;
var b = 15;
var c = 20;
var D = a + b + c;
console.log(D);
const price1 = 7;
const price2 = 5;
const value = price1 + price2;
console.log(value);
let carname = "volvo";
console.log(carname);
let name = "volvo", person = "elsa", price = 500;
console.log(person);
let car = "thar";
price = "2500";
Company = "mahindra";
console.log(Company);
let vehicle;
console.log(vehicle);
let $$$ = 10;
let $Num = 10;
console.log($$$ + $Num);
var x = 10; 
{
    var x = 5;
}
console.log(x);
const road = { type: "fiat", model: "500", color: "white" };
road.color = "blue";
road.owner = "Elsa";
console.log(road.color);