x = 5;
y = 6;
z = 7;
a = x + y + z;
console.log(a);
var a = 10;
var b = 15;
var c = 20;
var D = a + b + c;
console.log(D);
const price1 = 7;
const price2 = 5;
const value = price1 + price2;
console.log(value);